#########################################################Spring#########################################################
#spring:
#    application:
#        name: snacks-assistant-consumer
#server:
#  port: 8083
##########################################################eureka########################################################
eureka:
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registryFetchIntervalSeconds: 5 #5秒抓取一次注册信息
      #defaultZone: http://localhost:8761/eureka/

##########################################################logging#######################################################
logging:
  level:
     com.netflix: DEBUG

#########################################################fegin##########################################################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
#########################################################hystrix########################################################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #超时时间，超时后执行回退逻辑
      circuitBreaker:
        requestVolumeThreshold: 3   #请求3次内，超过一半的时候断路，则将断路器开启
  threadpool:
    default:
      coreSize: 10  #并发执行的最大线程数，默认10
#########################################################endpoints######################################################
## 开启消息跟踪
spring:
  cloud:
    bus:
      trace:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
