########################################################port############################################################
server:
  port: 9000
##########################################################zuul##########################################################
zuul:
  routes:
    snacks-assistant-consumer:
      path: /snacks-assistant-consumer/*
      serviceId: snacks-assistant-consumer
    snacks-assistant-user:
      path: /snacks-assistant-user/*
      serviceId: snacks-assistant-user
##########################################################eureka########################################################
eureka:
  client:
    registryFetchIntervalSeconds: 5 #5秒抓取一次注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#############################################################routes####################################################
management:
  endpoints:
    web:
      exposure:
        include: info,health,routes,filters
#######################################################config_refresh###################################################
spring:
  cloud:
    bus:
      trace:
        enabled: true  #跟踪总线事件
#######################################################sleuth_zipkin###################################################
spring:
  sleuth:
    sampler:
      probability: 1.0 #sleuth采样比例
  zipkin:
    enabled: true
    rabbitmq:
      queue: zipkin
###########################################################RabbitMQ#####################################################
#设置MQ用于监听配置刷新和发送sleuth跟踪信息
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest