###################################################Spring###############################################################
# mybatis_config
mybatis:
  mapper-locations: classpath:mapping/*.xml

##############################################################eureka####################################################
eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10 #这里是设置多久更新一次健康状态到Eureka服务器上
  instance:
    leaseRenewalIntervalInSeconds: 5 #健康相关配置，心跳监测5秒一次。
    leaseExpirationDurationInSeconds: 10 #如果超过10秒没有给服务器发送心跳请求，则服务器将剔除该实例
    metadata-map:
      company-name: coconason
#############################################################logging####################################################
logging:
  level:
    root: DEBUG
    #com.netflix: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    #org.springframework.web.servlet.DispatcherServlet: DEBUG
#########################################################endpoints######################################################
## 开启消息跟踪
spring:
  cloud:
    bus:
      trace:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

########################################################log4j2##########################################################
#asyncLogger:
#  ringBufferSize: 10000
#asyncLoggerConfig:
#  ringBufferSize: 10000
#log4j2:
#  asyncQueueFullPolicy: Discard
#  discardThreshold: DEBUG

########################################################################################################################
spring:
  sleuth:
    sampler:
      probability: 1.0 #sleuth采样比例
    #http:
    #  legacy:
    #    enabled: true
  zipkin:
    #base-url: http://127.0.0.1:9411
    enabled: true
    rabbitmq:
      queue: zipkin
########################################################datasource######################################################
spring:
  datasource:
    name: era
    url: jdbc:mysql://192.168.244.133:3306/snacks_user_info?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: 2zhlmcl!HBLSQT
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver