##########################################################eureka########################################################
eureka:
  client:
    registryFetchIntervalSeconds: 30 #30秒抓取一次注册信息
##########################################################logging#######################################################
logging:
  level:
    root: DEBUG
#    com.netflix: DEBUG
    org.springframework.cloud.sleuth: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG

#########################################################fegin##########################################################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
#########################################################hystrix########################################################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #超时时间，超时后执行回退逻辑
      circuitBreaker:
        requestVolumeThreshold: 3   #请求3次内，超过一半的时候断路，则将断路器开启
  threadpool:
    default:
      coreSize: 10  #并发执行的最大线程数，默认10
#########################################################endpoints######################################################
## 开启消息跟踪
spring:
  cloud:
    bus:
      trace:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
spring:
    sleuth:
      sampler:
        probability: 1.0 #sleuth采样比例
      #http:
      #  legacy:
      #    enabled: true
    zipkin:
      enabled: true
      rabbitmq:
        queue: zipkin
    #  base-url: http://127.0.0.1:9411