
##########################################################zuul##########################################################
zuul:
  routes:
    snacks-assistant-consumer:
      path: /snacks-assistant-consumer/*
      serviceId: snacks-assistant-consumer
##########################################################eureka########################################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registryFetchIntervalSeconds: 5 #5秒抓取一次注册信息

#############################################################routes####################################################
management:
  endpoint:
    routes:
      enabled: true
    health:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,routes
