###################################################Spring###############################################################
# mybatis_config
mybatis:
  mapper-locations: classpath:mapping/*.xml

##############################################################eureka####################################################
eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 10 #这里是设置多久更新一次健康状态到Eureka服务器上
  instance:
    leaseRenewalIntervalInSeconds: 5 #健康相关配置，心跳监测5秒一次。
    leaseExpirationDurationInSeconds: 10 #如果超过10秒没有给服务器发送心跳请求，则服务器将剔除该实例
    metadata-map:
      company-name: coconason
#############################################################logging####################################################
logging:
  level:
    com.netflix: DEBUG
#########################################################endpoints######################################################
## 开启消息跟踪
spring:
  cloud:
    bus:
      trace:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
########################################################log4j2##########################################################
#asyncLogger:
#  ringBufferSize: 10000
#asyncLoggerConfig:
#  ringBufferSize: 10000
#log4j2:
#  asyncQueueFullPolicy: Discard
#  discardThreshold: DEBUG