##########################################################zuul##########################################################
zuul:
  routes:
    snacks-assistant-consumer:
      path: /snacks-assistant-consumer/*
      serviceId: snacks-assistant-consumer
##########################################################eureka########################################################
eureka:
  client:
    registryFetchIntervalSeconds: 5 #5秒抓取一次注册信息

#############################################################routes####################################################
management:
  endpoint:
    routes:
      enabled: true
    health:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,routes
#########################################################endpoints######################################################
## 开启消息跟踪
spring:
  cloud:
    bus:
      trace:
        enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#############################################################logging####################################################
logging:
  level:
    com.netflix: WARN