#######################################################server###########################################################
server:
  port: 9411
##########################################################eureka########################################################
eureka:
  client:
    registryFetchIntervalSeconds: 30 #30秒抓取一次注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#####################################################zipkin-server######################################################
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin