package com.coconason.snacksassistantgoods.vo;

import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.Date;

public class SnacksInfoVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.name
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.des
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.nutrition_information
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    @Pattern(regexp = "^\\{.*\\}$")
    private String nutritionInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.recipe
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    @Pattern(regexp = "^[一-龥]*(\\|[一-龥]*)*")
    private String recipe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.producer
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String producer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.owner
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.trafficker
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String trafficker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.quantity
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.snacks_types_id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private Long snacksTypesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.batche_num
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private Integer batchsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.produce_date
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private Date produceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.code
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_info.picture
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    @Pattern(regexp ="((http|sftp|ftp|https)://)(([a-zA-Z0-9\\._-]+\\.[a-zA-Z]{2,6})|([0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}))(:[0-9]{1,4})*(/[a-zA-Z0-9\\&%_\\./-~-]*)?")
    private String picture;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.id
     *
     * @return the value of snacks_info.id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.id
     *
     * @param id the value for snacks_info.id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.name
     *
     * @return the value of snacks_info.name
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.name
     *
     * @param name the value for snacks_info.name
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.des
     *
     * @return the value of snacks_info.des
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.des
     *
     * @param des the value for snacks_info.des
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.nutrition_information
     *
     * @return the value of snacks_info.nutrition_information
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getNutritionInformation() {
        return nutritionInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.nutrition_information
     *
     * @param nutritionInformation the value for snacks_info.nutrition_information
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setNutritionInformation(String nutritionInformation) {
        this.nutritionInformation = nutritionInformation == null ? null : nutritionInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.recipe
     *
     * @return the value of snacks_info.recipe
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getRecipe() {
        return recipe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.recipe
     *
     * @param recipe the value for snacks_info.recipe
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setRecipe(String recipe) {
        this.recipe = recipe == null ? null : recipe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.producer
     *
     * @return the value of snacks_info.producer
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.producer
     *
     * @param producer the value for snacks_info.producer
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setProducer(String producer) {
        this.producer = producer == null ? null : producer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.owner
     *
     * @return the value of snacks_info.owner
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.owner
     *
     * @param owner the value for snacks_info.owner
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.trafficker
     *
     * @return the value of snacks_info.trafficker
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getTrafficker() {
        return trafficker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.trafficker
     *
     * @param trafficker the value for snacks_info.trafficker
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setTrafficker(String trafficker) {
        this.trafficker = trafficker == null ? null : trafficker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.quantity
     *
     * @return the value of snacks_info.quantity
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.quantity
     *
     * @param quantity the value for snacks_info.quantity
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.snacks_types_id
     *
     * @return the value of snacks_info.snacks_types_id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public Long getSnacksTypesId() {
        return snacksTypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.snacks_types_id
     *
     * @param snacksTypesId the value for snacks_info.snacks_types_id
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setSnacksTypesId(Long snacksTypesId) {
        this.snacksTypesId = snacksTypesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.batche_num
     *
     * @return the value of snacks_info.batche_num
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public Integer getBatchsNum() {
        return batchsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.batche_num
     *
     * @param batchsNum the value for snacks_info.batche_num
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setBatchsNum(Integer batchsNum) {
        this.batchsNum = batchsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.produce_date
     *
     * @return the value of snacks_info.produce_date
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public Date getProduceDate() {
        return produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.produce_date
     *
     * @param produceDate the value for snacks_info.produce_date
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setProduceDate(Date produceDate) {
        this.produceDate = produceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.code
     *
     * @return the value of snacks_info.code
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.code
     *
     * @param code the value for snacks_info.code
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_info.picture
     *
     * @return the value of snacks_info.picture
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_info.picture
     *
     * @param picture the value for snacks_info.picture
     *
     * @mbggenerated Thu May 10 11:34:42 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

}

