package com.coconason.snacksassistantuser.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListIsNull() {
            addCriterion("favorite_food_id_list is null");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListIsNotNull() {
            addCriterion("favorite_food_id_list is not null");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListEqualTo(String value) {
            addCriterion("favorite_food_id_list =", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListNotEqualTo(String value) {
            addCriterion("favorite_food_id_list <>", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListGreaterThan(String value) {
            addCriterion("favorite_food_id_list >", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListGreaterThanOrEqualTo(String value) {
            addCriterion("favorite_food_id_list >=", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListLessThan(String value) {
            addCriterion("favorite_food_id_list <", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListLessThanOrEqualTo(String value) {
            addCriterion("favorite_food_id_list <=", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListLike(String value) {
            addCriterion("favorite_food_id_list like", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListNotLike(String value) {
            addCriterion("favorite_food_id_list not like", value, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListIn(List<String> values) {
            addCriterion("favorite_food_id_list in", values, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListNotIn(List<String> values) {
            addCriterion("favorite_food_id_list not in", values, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListBetween(String value1, String value2) {
            addCriterion("favorite_food_id_list between", value1, value2, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andFavoriteFoodIdListNotBetween(String value1, String value2) {
            addCriterion("favorite_food_id_list not between", value1, value2, "favoriteFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListIsNull() {
            addCriterion("dislike_food_id_list is null");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListIsNotNull() {
            addCriterion("dislike_food_id_list is not null");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListEqualTo(String value) {
            addCriterion("dislike_food_id_list =", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListNotEqualTo(String value) {
            addCriterion("dislike_food_id_list <>", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListGreaterThan(String value) {
            addCriterion("dislike_food_id_list >", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListGreaterThanOrEqualTo(String value) {
            addCriterion("dislike_food_id_list >=", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListLessThan(String value) {
            addCriterion("dislike_food_id_list <", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListLessThanOrEqualTo(String value) {
            addCriterion("dislike_food_id_list <=", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListLike(String value) {
            addCriterion("dislike_food_id_list like", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListNotLike(String value) {
            addCriterion("dislike_food_id_list not like", value, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListIn(List<String> values) {
            addCriterion("dislike_food_id_list in", values, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListNotIn(List<String> values) {
            addCriterion("dislike_food_id_list not in", values, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListBetween(String value1, String value2) {
            addCriterion("dislike_food_id_list between", value1, value2, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andDislikeFoodIdListNotBetween(String value1, String value2) {
            addCriterion("dislike_food_id_list not between", value1, value2, "dislikeFoodIdList");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitIsNull() {
            addCriterion("consumption_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitIsNotNull() {
            addCriterion("consumption_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitEqualTo(Integer value) {
            addCriterion("consumption_upper_limit =", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitNotEqualTo(Integer value) {
            addCriterion("consumption_upper_limit <>", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitGreaterThan(Integer value) {
            addCriterion("consumption_upper_limit >", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("consumption_upper_limit >=", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitLessThan(Integer value) {
            addCriterion("consumption_upper_limit <", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitLessThanOrEqualTo(Integer value) {
            addCriterion("consumption_upper_limit <=", value, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitIn(List<Integer> values) {
            addCriterion("consumption_upper_limit in", values, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitNotIn(List<Integer> values) {
            addCriterion("consumption_upper_limit not in", values, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitBetween(Integer value1, Integer value2) {
            addCriterion("consumption_upper_limit between", value1, value2, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionUpperLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("consumption_upper_limit not between", value1, value2, "consumptionUpperLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitIsNull() {
            addCriterion("consumption_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitIsNotNull() {
            addCriterion("consumption_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitEqualTo(Integer value) {
            addCriterion("consumption_lower_limit =", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitNotEqualTo(Integer value) {
            addCriterion("consumption_lower_limit <>", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitGreaterThan(Integer value) {
            addCriterion("consumption_lower_limit >", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("consumption_lower_limit >=", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitLessThan(Integer value) {
            addCriterion("consumption_lower_limit <", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitLessThanOrEqualTo(Integer value) {
            addCriterion("consumption_lower_limit <=", value, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitIn(List<Integer> values) {
            addCriterion("consumption_lower_limit in", values, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitNotIn(List<Integer> values) {
            addCriterion("consumption_lower_limit not in", values, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitBetween(Integer value1, Integer value2) {
            addCriterion("consumption_lower_limit between", value1, value2, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andConsumptionLowerLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("consumption_lower_limit not between", value1, value2, "consumptionLowerLimit");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andRecipientIsNull() {
            addCriterion("recipient is null");
            return (Criteria) this;
        }

        public Criteria andRecipientIsNotNull() {
            addCriterion("recipient is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientEqualTo(String value) {
            addCriterion("recipient =", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotEqualTo(String value) {
            addCriterion("recipient <>", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientGreaterThan(String value) {
            addCriterion("recipient >", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientGreaterThanOrEqualTo(String value) {
            addCriterion("recipient >=", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientLessThan(String value) {
            addCriterion("recipient <", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientLessThanOrEqualTo(String value) {
            addCriterion("recipient <=", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientLike(String value) {
            addCriterion("recipient like", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotLike(String value) {
            addCriterion("recipient not like", value, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientIn(List<String> values) {
            addCriterion("recipient in", values, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotIn(List<String> values) {
            addCriterion("recipient not in", values, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientBetween(String value1, String value2) {
            addCriterion("recipient between", value1, value2, "recipient");
            return (Criteria) this;
        }

        public Criteria andRecipientNotBetween(String value1, String value2) {
            addCriterion("recipient not between", value1, value2, "recipient");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitIsNull() {
            addCriterion("reception_time_upper_limit is null");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitIsNotNull() {
            addCriterion("reception_time_upper_limit is not null");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit =", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitNotEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit <>", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitGreaterThan(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit >", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit >=", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitLessThan(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit <", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_upper_limit <=", value, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitIn(List<Date> values) {
            addCriterionForJDBCTime("reception_time_upper_limit in", values, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitNotIn(List<Date> values) {
            addCriterionForJDBCTime("reception_time_upper_limit not in", values, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("reception_time_upper_limit between", value1, value2, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeUpperLimitNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("reception_time_upper_limit not between", value1, value2, "receptionTimeUpperLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitIsNull() {
            addCriterion("reception_time_lower_limit is null");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitIsNotNull() {
            addCriterion("reception_time_lower_limit is not null");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit =", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitNotEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit <>", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitGreaterThan(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit >", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit >=", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitLessThan(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit <", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("reception_time_lower_limit <=", value, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitIn(List<Date> values) {
            addCriterionForJDBCTime("reception_time_lower_limit in", values, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitNotIn(List<Date> values) {
            addCriterionForJDBCTime("reception_time_lower_limit not in", values, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("reception_time_lower_limit between", value1, value2, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andReceptionTimeLowerLimitNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("reception_time_lower_limit not between", value1, value2, "receptionTimeLowerLimit");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateIsNull() {
            addCriterion("subscription_sate is null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateIsNotNull() {
            addCriterion("subscription_sate is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateEqualTo(Byte value) {
            addCriterion("subscription_sate =", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateNotEqualTo(Byte value) {
            addCriterion("subscription_sate <>", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateGreaterThan(Byte value) {
            addCriterion("subscription_sate >", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateGreaterThanOrEqualTo(Byte value) {
            addCriterion("subscription_sate >=", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateLessThan(Byte value) {
            addCriterion("subscription_sate <", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateLessThanOrEqualTo(Byte value) {
            addCriterion("subscription_sate <=", value, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateIn(List<Byte> values) {
            addCriterion("subscription_sate in", values, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateNotIn(List<Byte> values) {
            addCriterion("subscription_sate not in", values, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateBetween(Byte value1, Byte value2) {
            addCriterion("subscription_sate between", value1, value2, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionSateNotBetween(Byte value1, Byte value2) {
            addCriterion("subscription_sate not between", value1, value2, "subscriptionSate");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeIsNull() {
            addCriterion("subscription_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeIsNotNull() {
            addCriterion("subscription_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeEqualTo(Date value) {
            addCriterion("subscription_start_time =", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeNotEqualTo(Date value) {
            addCriterion("subscription_start_time <>", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeGreaterThan(Date value) {
            addCriterion("subscription_start_time >", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("subscription_start_time >=", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeLessThan(Date value) {
            addCriterion("subscription_start_time <", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("subscription_start_time <=", value, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeIn(List<Date> values) {
            addCriterion("subscription_start_time in", values, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeNotIn(List<Date> values) {
            addCriterion("subscription_start_time not in", values, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeBetween(Date value1, Date value2) {
            addCriterion("subscription_start_time between", value1, value2, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andSubscriptionStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("subscription_start_time not between", value1, value2, "subscriptionStartTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleIsNull() {
            addCriterion("delivery_cycle is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleIsNotNull() {
            addCriterion("delivery_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleEqualTo(Integer value) {
            addCriterion("delivery_cycle =", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleNotEqualTo(Integer value) {
            addCriterion("delivery_cycle <>", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleGreaterThan(Integer value) {
            addCriterion("delivery_cycle >", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("delivery_cycle >=", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleLessThan(Integer value) {
            addCriterion("delivery_cycle <", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleLessThanOrEqualTo(Integer value) {
            addCriterion("delivery_cycle <=", value, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleIn(List<Integer> values) {
            addCriterion("delivery_cycle in", values, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleNotIn(List<Integer> values) {
            addCriterion("delivery_cycle not in", values, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleBetween(Integer value1, Integer value2) {
            addCriterion("delivery_cycle between", value1, value2, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andDeliveryCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("delivery_cycle not between", value1, value2, "deliveryCycle");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Long value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Long value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Long value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Long value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Long value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Long> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Long> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Long value1, Long value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Long value1, Long value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated do_not_delete_during_merge Tue May 08 13:13:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Tue May 08 13:13:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}