package com.coconason.snacksassistantuser.dao;

import com.coconason.snacksassistantuser.po.AddressInfo;
import com.coconason.snacksassistantuser.po.AddressInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AddressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int countByExample(AddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int deleteByExample(AddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int insert(AddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int insertSelective(AddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    List<AddressInfo> selectByExample(AddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    AddressInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") AddressInfo record, @Param("example") AddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int updateByExample(@Param("record") AddressInfo record, @Param("example") AddressInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int updateByPrimaryKeySelective(AddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_info
     *
     * @mbggenerated Fri Jun 08 11:43:17 CST 2018
     */
    int updateByPrimaryKey(AddressInfo record);
}