server:
  port: 8899
spring:
  application:
    name: snacks-assistant-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wgy8283335/snacks-assistant/
          search-paths: configuration-files
          username: wgy8283335@126.com
          password: Cc8265739
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/