package com.coconason.snacksassistantgoods.po;

import java.io.Serializable;
import java.util.Date;

public class SnacksTypes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.id
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.name
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.des
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.type_first_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String typeFirstLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.type_second_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String typeSecondLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.type_third_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String typeThirdLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.type_forth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String typeForthLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.type_fifth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private String typeFifthLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.deleted
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.update_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snacks_types.create_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.id
     *
     * @return the value of snacks_types.id
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.id
     *
     * @param id the value for snacks_types.id
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.name
     *
     * @return the value of snacks_types.name
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.name
     *
     * @param name the value for snacks_types.name
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.des
     *
     * @return the value of snacks_types.des
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.des
     *
     * @param des the value for snacks_types.des
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.type_first_level
     *
     * @return the value of snacks_types.type_first_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getTypeFirstLevel() {
        return typeFirstLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.type_first_level
     *
     * @param typeFirstLevel the value for snacks_types.type_first_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setTypeFirstLevel(String typeFirstLevel) {
        this.typeFirstLevel = typeFirstLevel == null ? null : typeFirstLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.type_second_level
     *
     * @return the value of snacks_types.type_second_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getTypeSecondLevel() {
        return typeSecondLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.type_second_level
     *
     * @param typeSecondLevel the value for snacks_types.type_second_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setTypeSecondLevel(String typeSecondLevel) {
        this.typeSecondLevel = typeSecondLevel == null ? null : typeSecondLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.type_third_level
     *
     * @return the value of snacks_types.type_third_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getTypeThirdLevel() {
        return typeThirdLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.type_third_level
     *
     * @param typeThirdLevel the value for snacks_types.type_third_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setTypeThirdLevel(String typeThirdLevel) {
        this.typeThirdLevel = typeThirdLevel == null ? null : typeThirdLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.type_forth_level
     *
     * @return the value of snacks_types.type_forth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getTypeForthLevel() {
        return typeForthLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.type_forth_level
     *
     * @param typeForthLevel the value for snacks_types.type_forth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setTypeForthLevel(String typeForthLevel) {
        this.typeForthLevel = typeForthLevel == null ? null : typeForthLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.type_fifth_level
     *
     * @return the value of snacks_types.type_fifth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getTypeFifthLevel() {
        return typeFifthLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.type_fifth_level
     *
     * @param typeFifthLevel the value for snacks_types.type_fifth_level
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setTypeFifthLevel(String typeFifthLevel) {
        this.typeFifthLevel = typeFifthLevel == null ? null : typeFifthLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.deleted
     *
     * @return the value of snacks_types.deleted
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.deleted
     *
     * @param deleted the value for snacks_types.deleted
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.update_time
     *
     * @return the value of snacks_types.update_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.update_time
     *
     * @param updateTime the value for snacks_types.update_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snacks_types.create_time
     *
     * @return the value of snacks_types.create_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snacks_types.create_time
     *
     * @param createTime the value for snacks_types.create_time
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}