package com.coconason.snacksassistantgoods.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SnacksInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public SnacksInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andItemCostIsNull() {
            addCriterion("item_cost is null");
            return (Criteria) this;
        }

        public Criteria andItemCostIsNotNull() {
            addCriterion("item_cost is not null");
            return (Criteria) this;
        }

        public Criteria andItemCostEqualTo(Integer value) {
            addCriterion("item_cost =", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostNotEqualTo(Integer value) {
            addCriterion("item_cost <>", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostGreaterThan(Integer value) {
            addCriterion("item_cost >", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_cost >=", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostLessThan(Integer value) {
            addCriterion("item_cost <", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostLessThanOrEqualTo(Integer value) {
            addCriterion("item_cost <=", value, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostIn(List<Integer> values) {
            addCriterion("item_cost in", values, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostNotIn(List<Integer> values) {
            addCriterion("item_cost not in", values, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostBetween(Integer value1, Integer value2) {
            addCriterion("item_cost between", value1, value2, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemCostNotBetween(Integer value1, Integer value2) {
            addCriterion("item_cost not between", value1, value2, "itemCost");
            return (Criteria) this;
        }

        public Criteria andItemPriceIsNull() {
            addCriterion("item_price is null");
            return (Criteria) this;
        }

        public Criteria andItemPriceIsNotNull() {
            addCriterion("item_price is not null");
            return (Criteria) this;
        }

        public Criteria andItemPriceEqualTo(Integer value) {
            addCriterion("item_price =", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceNotEqualTo(Integer value) {
            addCriterion("item_price <>", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceGreaterThan(Integer value) {
            addCriterion("item_price >", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_price >=", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceLessThan(Integer value) {
            addCriterion("item_price <", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceLessThanOrEqualTo(Integer value) {
            addCriterion("item_price <=", value, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceIn(List<Integer> values) {
            addCriterion("item_price in", values, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceNotIn(List<Integer> values) {
            addCriterion("item_price not in", values, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceBetween(Integer value1, Integer value2) {
            addCriterion("item_price between", value1, value2, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andItemPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("item_price not between", value1, value2, "itemPrice");
            return (Criteria) this;
        }

        public Criteria andDesIsNull() {
            addCriterion("des is null");
            return (Criteria) this;
        }

        public Criteria andDesIsNotNull() {
            addCriterion("des is not null");
            return (Criteria) this;
        }

        public Criteria andDesEqualTo(String value) {
            addCriterion("des =", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotEqualTo(String value) {
            addCriterion("des <>", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThan(String value) {
            addCriterion("des >", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThanOrEqualTo(String value) {
            addCriterion("des >=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThan(String value) {
            addCriterion("des <", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThanOrEqualTo(String value) {
            addCriterion("des <=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLike(String value) {
            addCriterion("des like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotLike(String value) {
            addCriterion("des not like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesIn(List<String> values) {
            addCriterion("des in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotIn(List<String> values) {
            addCriterion("des not in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesBetween(String value1, String value2) {
            addCriterion("des between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotBetween(String value1, String value2) {
            addCriterion("des not between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationIsNull() {
            addCriterion("nutrition_information is null");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationIsNotNull() {
            addCriterion("nutrition_information is not null");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationEqualTo(String value) {
            addCriterion("nutrition_information =", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationNotEqualTo(String value) {
            addCriterion("nutrition_information <>", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationGreaterThan(String value) {
            addCriterion("nutrition_information >", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationGreaterThanOrEqualTo(String value) {
            addCriterion("nutrition_information >=", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationLessThan(String value) {
            addCriterion("nutrition_information <", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationLessThanOrEqualTo(String value) {
            addCriterion("nutrition_information <=", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationLike(String value) {
            addCriterion("nutrition_information like", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationNotLike(String value) {
            addCriterion("nutrition_information not like", value, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationIn(List<String> values) {
            addCriterion("nutrition_information in", values, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationNotIn(List<String> values) {
            addCriterion("nutrition_information not in", values, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationBetween(String value1, String value2) {
            addCriterion("nutrition_information between", value1, value2, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andNutritionInformationNotBetween(String value1, String value2) {
            addCriterion("nutrition_information not between", value1, value2, "nutritionInformation");
            return (Criteria) this;
        }

        public Criteria andRecipeIsNull() {
            addCriterion("recipe is null");
            return (Criteria) this;
        }

        public Criteria andRecipeIsNotNull() {
            addCriterion("recipe is not null");
            return (Criteria) this;
        }

        public Criteria andRecipeEqualTo(String value) {
            addCriterion("recipe =", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeNotEqualTo(String value) {
            addCriterion("recipe <>", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeGreaterThan(String value) {
            addCriterion("recipe >", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeGreaterThanOrEqualTo(String value) {
            addCriterion("recipe >=", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeLessThan(String value) {
            addCriterion("recipe <", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeLessThanOrEqualTo(String value) {
            addCriterion("recipe <=", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeLike(String value) {
            addCriterion("recipe like", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeNotLike(String value) {
            addCriterion("recipe not like", value, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeIn(List<String> values) {
            addCriterion("recipe in", values, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeNotIn(List<String> values) {
            addCriterion("recipe not in", values, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeBetween(String value1, String value2) {
            addCriterion("recipe between", value1, value2, "recipe");
            return (Criteria) this;
        }

        public Criteria andRecipeNotBetween(String value1, String value2) {
            addCriterion("recipe not between", value1, value2, "recipe");
            return (Criteria) this;
        }

        public Criteria andProducerIsNull() {
            addCriterion("producer is null");
            return (Criteria) this;
        }

        public Criteria andProducerIsNotNull() {
            addCriterion("producer is not null");
            return (Criteria) this;
        }

        public Criteria andProducerEqualTo(String value) {
            addCriterion("producer =", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotEqualTo(String value) {
            addCriterion("producer <>", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerGreaterThan(String value) {
            addCriterion("producer >", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerGreaterThanOrEqualTo(String value) {
            addCriterion("producer >=", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLessThan(String value) {
            addCriterion("producer <", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLessThanOrEqualTo(String value) {
            addCriterion("producer <=", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerLike(String value) {
            addCriterion("producer like", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotLike(String value) {
            addCriterion("producer not like", value, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerIn(List<String> values) {
            addCriterion("producer in", values, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotIn(List<String> values) {
            addCriterion("producer not in", values, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerBetween(String value1, String value2) {
            addCriterion("producer between", value1, value2, "producer");
            return (Criteria) this;
        }

        public Criteria andProducerNotBetween(String value1, String value2) {
            addCriterion("producer not between", value1, value2, "producer");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("owner is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("owner is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("owner =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("owner <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("owner >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("owner >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("owner <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("owner <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("owner like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("owner not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("owner in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("owner not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("owner between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("owner not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andTraffickerIsNull() {
            addCriterion("trafficker is null");
            return (Criteria) this;
        }

        public Criteria andTraffickerIsNotNull() {
            addCriterion("trafficker is not null");
            return (Criteria) this;
        }

        public Criteria andTraffickerEqualTo(String value) {
            addCriterion("trafficker =", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerNotEqualTo(String value) {
            addCriterion("trafficker <>", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerGreaterThan(String value) {
            addCriterion("trafficker >", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerGreaterThanOrEqualTo(String value) {
            addCriterion("trafficker >=", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerLessThan(String value) {
            addCriterion("trafficker <", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerLessThanOrEqualTo(String value) {
            addCriterion("trafficker <=", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerLike(String value) {
            addCriterion("trafficker like", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerNotLike(String value) {
            addCriterion("trafficker not like", value, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerIn(List<String> values) {
            addCriterion("trafficker in", values, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerNotIn(List<String> values) {
            addCriterion("trafficker not in", values, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerBetween(String value1, String value2) {
            addCriterion("trafficker between", value1, value2, "trafficker");
            return (Criteria) this;
        }

        public Criteria andTraffickerNotBetween(String value1, String value2) {
            addCriterion("trafficker not between", value1, value2, "trafficker");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdIsNull() {
            addCriterion("snacks_types_id is null");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdIsNotNull() {
            addCriterion("snacks_types_id is not null");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdEqualTo(Long value) {
            addCriterion("snacks_types_id =", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdNotEqualTo(Long value) {
            addCriterion("snacks_types_id <>", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdGreaterThan(Long value) {
            addCriterion("snacks_types_id >", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdGreaterThanOrEqualTo(Long value) {
            addCriterion("snacks_types_id >=", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdLessThan(Long value) {
            addCriterion("snacks_types_id <", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdLessThanOrEqualTo(Long value) {
            addCriterion("snacks_types_id <=", value, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdIn(List<Long> values) {
            addCriterion("snacks_types_id in", values, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdNotIn(List<Long> values) {
            addCriterion("snacks_types_id not in", values, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdBetween(Long value1, Long value2) {
            addCriterion("snacks_types_id between", value1, value2, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andSnacksTypesIdNotBetween(Long value1, Long value2) {
            addCriterion("snacks_types_id not between", value1, value2, "snacksTypesId");
            return (Criteria) this;
        }

        public Criteria andBatchsNumIsNull() {
            addCriterion("batchs_num is null");
            return (Criteria) this;
        }

        public Criteria andBatchsNumIsNotNull() {
            addCriterion("batchs_num is not null");
            return (Criteria) this;
        }

        public Criteria andBatchsNumEqualTo(Integer value) {
            addCriterion("batchs_num =", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumNotEqualTo(Integer value) {
            addCriterion("batchs_num <>", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumGreaterThan(Integer value) {
            addCriterion("batchs_num >", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("batchs_num >=", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumLessThan(Integer value) {
            addCriterion("batchs_num <", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumLessThanOrEqualTo(Integer value) {
            addCriterion("batchs_num <=", value, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumIn(List<Integer> values) {
            addCriterion("batchs_num in", values, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumNotIn(List<Integer> values) {
            addCriterion("batchs_num not in", values, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumBetween(Integer value1, Integer value2) {
            addCriterion("batchs_num between", value1, value2, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andBatchsNumNotBetween(Integer value1, Integer value2) {
            addCriterion("batchs_num not between", value1, value2, "batchsNum");
            return (Criteria) this;
        }

        public Criteria andProduceDateIsNull() {
            addCriterion("produce_date is null");
            return (Criteria) this;
        }

        public Criteria andProduceDateIsNotNull() {
            addCriterion("produce_date is not null");
            return (Criteria) this;
        }

        public Criteria andProduceDateEqualTo(Date value) {
            addCriterion("produce_date =", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateNotEqualTo(Date value) {
            addCriterion("produce_date <>", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateGreaterThan(Date value) {
            addCriterion("produce_date >", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateGreaterThanOrEqualTo(Date value) {
            addCriterion("produce_date >=", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateLessThan(Date value) {
            addCriterion("produce_date <", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateLessThanOrEqualTo(Date value) {
            addCriterion("produce_date <=", value, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateIn(List<Date> values) {
            addCriterion("produce_date in", values, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateNotIn(List<Date> values) {
            addCriterion("produce_date not in", values, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateBetween(Date value1, Date value2) {
            addCriterion("produce_date between", value1, value2, "produceDate");
            return (Criteria) this;
        }

        public Criteria andProduceDateNotBetween(Date value1, Date value2) {
            addCriterion("produce_date not between", value1, value2, "produceDate");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 13 16:53:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_info
     *
     * @mbggenerated Wed Jun 13 16:53:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}