package com.coconason.snacksassistantgoods.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SnacksTypesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public SnacksTypesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDesIsNull() {
            addCriterion("des is null");
            return (Criteria) this;
        }

        public Criteria andDesIsNotNull() {
            addCriterion("des is not null");
            return (Criteria) this;
        }

        public Criteria andDesEqualTo(String value) {
            addCriterion("des =", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotEqualTo(String value) {
            addCriterion("des <>", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThan(String value) {
            addCriterion("des >", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThanOrEqualTo(String value) {
            addCriterion("des >=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThan(String value) {
            addCriterion("des <", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThanOrEqualTo(String value) {
            addCriterion("des <=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLike(String value) {
            addCriterion("des like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotLike(String value) {
            addCriterion("des not like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesIn(List<String> values) {
            addCriterion("des in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotIn(List<String> values) {
            addCriterion("des not in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesBetween(String value1, String value2) {
            addCriterion("des between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotBetween(String value1, String value2) {
            addCriterion("des not between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelIsNull() {
            addCriterion("type_first_level is null");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelIsNotNull() {
            addCriterion("type_first_level is not null");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelEqualTo(String value) {
            addCriterion("type_first_level =", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelNotEqualTo(String value) {
            addCriterion("type_first_level <>", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelGreaterThan(String value) {
            addCriterion("type_first_level >", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelGreaterThanOrEqualTo(String value) {
            addCriterion("type_first_level >=", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelLessThan(String value) {
            addCriterion("type_first_level <", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelLessThanOrEqualTo(String value) {
            addCriterion("type_first_level <=", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelLike(String value) {
            addCriterion("type_first_level like", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelNotLike(String value) {
            addCriterion("type_first_level not like", value, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelIn(List<String> values) {
            addCriterion("type_first_level in", values, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelNotIn(List<String> values) {
            addCriterion("type_first_level not in", values, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelBetween(String value1, String value2) {
            addCriterion("type_first_level between", value1, value2, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFirstLevelNotBetween(String value1, String value2) {
            addCriterion("type_first_level not between", value1, value2, "typeFirstLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelIsNull() {
            addCriterion("type_second_level is null");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelIsNotNull() {
            addCriterion("type_second_level is not null");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelEqualTo(String value) {
            addCriterion("type_second_level =", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelNotEqualTo(String value) {
            addCriterion("type_second_level <>", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelGreaterThan(String value) {
            addCriterion("type_second_level >", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelGreaterThanOrEqualTo(String value) {
            addCriterion("type_second_level >=", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelLessThan(String value) {
            addCriterion("type_second_level <", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelLessThanOrEqualTo(String value) {
            addCriterion("type_second_level <=", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelLike(String value) {
            addCriterion("type_second_level like", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelNotLike(String value) {
            addCriterion("type_second_level not like", value, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelIn(List<String> values) {
            addCriterion("type_second_level in", values, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelNotIn(List<String> values) {
            addCriterion("type_second_level not in", values, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelBetween(String value1, String value2) {
            addCriterion("type_second_level between", value1, value2, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeSecondLevelNotBetween(String value1, String value2) {
            addCriterion("type_second_level not between", value1, value2, "typeSecondLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelIsNull() {
            addCriterion("type_third_level is null");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelIsNotNull() {
            addCriterion("type_third_level is not null");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelEqualTo(String value) {
            addCriterion("type_third_level =", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelNotEqualTo(String value) {
            addCriterion("type_third_level <>", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelGreaterThan(String value) {
            addCriterion("type_third_level >", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelGreaterThanOrEqualTo(String value) {
            addCriterion("type_third_level >=", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelLessThan(String value) {
            addCriterion("type_third_level <", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelLessThanOrEqualTo(String value) {
            addCriterion("type_third_level <=", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelLike(String value) {
            addCriterion("type_third_level like", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelNotLike(String value) {
            addCriterion("type_third_level not like", value, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelIn(List<String> values) {
            addCriterion("type_third_level in", values, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelNotIn(List<String> values) {
            addCriterion("type_third_level not in", values, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelBetween(String value1, String value2) {
            addCriterion("type_third_level between", value1, value2, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeThirdLevelNotBetween(String value1, String value2) {
            addCriterion("type_third_level not between", value1, value2, "typeThirdLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelIsNull() {
            addCriterion("type_forth_level is null");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelIsNotNull() {
            addCriterion("type_forth_level is not null");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelEqualTo(String value) {
            addCriterion("type_forth_level =", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelNotEqualTo(String value) {
            addCriterion("type_forth_level <>", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelGreaterThan(String value) {
            addCriterion("type_forth_level >", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelGreaterThanOrEqualTo(String value) {
            addCriterion("type_forth_level >=", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelLessThan(String value) {
            addCriterion("type_forth_level <", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelLessThanOrEqualTo(String value) {
            addCriterion("type_forth_level <=", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelLike(String value) {
            addCriterion("type_forth_level like", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelNotLike(String value) {
            addCriterion("type_forth_level not like", value, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelIn(List<String> values) {
            addCriterion("type_forth_level in", values, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelNotIn(List<String> values) {
            addCriterion("type_forth_level not in", values, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelBetween(String value1, String value2) {
            addCriterion("type_forth_level between", value1, value2, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeForthLevelNotBetween(String value1, String value2) {
            addCriterion("type_forth_level not between", value1, value2, "typeForthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelIsNull() {
            addCriterion("type_fifth_level is null");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelIsNotNull() {
            addCriterion("type_fifth_level is not null");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelEqualTo(String value) {
            addCriterion("type_fifth_level =", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelNotEqualTo(String value) {
            addCriterion("type_fifth_level <>", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelGreaterThan(String value) {
            addCriterion("type_fifth_level >", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelGreaterThanOrEqualTo(String value) {
            addCriterion("type_fifth_level >=", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelLessThan(String value) {
            addCriterion("type_fifth_level <", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelLessThanOrEqualTo(String value) {
            addCriterion("type_fifth_level <=", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelLike(String value) {
            addCriterion("type_fifth_level like", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelNotLike(String value) {
            addCriterion("type_fifth_level not like", value, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelIn(List<String> values) {
            addCriterion("type_fifth_level in", values, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelNotIn(List<String> values) {
            addCriterion("type_fifth_level not in", values, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelBetween(String value1, String value2) {
            addCriterion("type_fifth_level between", value1, value2, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andTypeFifthLevelNotBetween(String value1, String value2) {
            addCriterion("type_fifth_level not between", value1, value2, "typeFifthLevel");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_types
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 27 14:21:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table snacks_types
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}