package com.coconason.snacksassistantgoods.dao;

import com.coconason.snacksassistantgoods.po.SnacksInfo;
import com.coconason.snacksassistantgoods.po.SnacksInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SnacksInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int countByExample(SnacksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int deleteByExample(SnacksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int insert(SnacksInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int insertSelective(SnacksInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    List<SnacksInfo> selectByExample(SnacksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    SnacksInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SnacksInfo record, @Param("example") SnacksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int updateByExample(@Param("record") SnacksInfo record, @Param("example") SnacksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int updateByPrimaryKeySelective(SnacksInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_info
     *
     * @mbggenerated Thu May 10 12:00:22 CST 2018
     */
    int updateByPrimaryKey(SnacksInfo record);
}