package com.coconason.snacksassistantgoods.dao;

import com.coconason.snacksassistantgoods.po.SnacksInventory;
import com.coconason.snacksassistantgoods.po.SnacksInventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SnacksInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int countByExample(SnacksInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int deleteByExample(SnacksInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int insert(SnacksInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int insertSelective(SnacksInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    List<SnacksInventory> selectByExample(SnacksInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    SnacksInventory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") SnacksInventory record, @Param("example") SnacksInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int updateByExample(@Param("record") SnacksInventory record, @Param("example") SnacksInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int updateByPrimaryKeySelective(SnacksInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table snacks_inventory
     *
     * @mbggenerated Mon Aug 27 14:21:49 CST 2018
     */
    int updateByPrimaryKey(SnacksInventory record);
}