package com.coconason.snacksassistantcommon.vo;

import javax.validation.constraints.Pattern;
import java.io.Serializable;
import java.util.Date;

public class OrderInfoVo implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    @Pattern(regexp = "^\\{.*\\}$")
    private String goods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.discount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Float discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.deduction
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Integer deduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.user_id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.recipient
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private String recipient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.phone_number
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.address
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    @Pattern(regexp = "^\\{.*\\}$")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.reception_time_upper_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Date receptionTimeUpperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.reception_time_lower_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Date receptionTimeLowerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_receive_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    private Date goodsReceiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.goods_send_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    private Date goodsSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods
     *
     * @return the value of order_info.goods
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods
     *
     * @param goods the value for order_info.goods
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setGoods(String goods) {
        this.goods = goods == null ? null : goods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount
     *
     * @return the value of order_info.amount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount
     *
     * @param amount the value for order_info.amount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.discount
     *
     * @return the value of order_info.discount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.discount
     *
     * @param discount the value for order_info.discount
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.deduction
     *
     * @return the value of order_info.deduction
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Integer getDeduction() {
        return deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.deduction
     *
     * @param deduction the value for order_info.deduction
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setDeduction(Integer deduction) {
        this.deduction = deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total
     *
     * @return the value of order_info.total
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total
     *
     * @param total the value for order_info.total
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.user_id
     *
     * @return the value of order_info.user_id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.user_id
     *
     * @param userId the value for order_info.user_id
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.recipient
     *
     * @return the value of order_info.recipient
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.recipient
     *
     * @param recipient the value for order_info.recipient
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient == null ? null : recipient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.phone_number
     *
     * @return the value of order_info.phone_number
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.phone_number
     *
     * @param phoneNumber the value for order_info.phone_number
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.address
     *
     * @return the value of order_info.address
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.address
     *
     * @param address the value for order_info.address
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.reception_time_upper_limit
     *
     * @return the value of order_info.reception_time_upper_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Date getReceptionTimeUpperLimit() {
        return receptionTimeUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.reception_time_upper_limit
     *
     * @param receptionTimeUpperLimit the value for order_info.reception_time_upper_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setReceptionTimeUpperLimit(Date receptionTimeUpperLimit) {
        this.receptionTimeUpperLimit = receptionTimeUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.reception_time_lower_limit
     *
     * @return the value of order_info.reception_time_lower_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Date getReceptionTimeLowerLimit() {
        return receptionTimeLowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.reception_time_lower_limit
     *
     * @param receptionTimeLowerLimit the value for order_info.reception_time_lower_limit
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setReceptionTimeLowerLimit(Date receptionTimeLowerLimit) {
        this.receptionTimeLowerLimit = receptionTimeLowerLimit;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_receive_time
     *
     * @return the value of order_info.goods_receive_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    public Date getGoodsReceiveTime() {
        return goodsReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_receive_time
     *
     * @param goodsReceiveTime the value for order_info.goods_receive_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    public void setGoodsReceiveTime(Date goodsReceiveTime) {
        this.goodsReceiveTime = goodsReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.goods_send_time
     *
     * @return the value of order_info.goods_send_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    public Date getGoodsSendTime() {
        return goodsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.goods_send_time
     *
     * @param goodsSendTime the value for order_info.goods_send_time
     *
     * @mbggenerated Tue Jun 12 17:01:14 CST 2018
     */
    public void setGoodsSendTime(Date goodsSendTime) {
        this.goodsSendTime = goodsSendTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.deleted
     *
     * @return the value of order_info.deleted
     *
     * @mbggenerated Thu May 10 17:10:46 CST 2018
     */
}