package com.coconason.snacksassistantcommon.vo;

import java.io.Serializable;
import java.util.Date;

public class UserInfoVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.favorite_food_id_list
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String favoriteFoodIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.dislike_food_id_list
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String dislikeFoodIdList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.consumption_upper_limit
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Integer consumptionUpperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.consumption_lower_limit
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Integer consumptionLowerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.recipient
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String recipient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reception_time_upper_limit
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String receptionTimeUpperLimit;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.reception_time_lower_limit
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private String receptionTimeLowerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subscription_sate
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Byte subscriptionSate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subscription_start_time
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Date subscriptionStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delivery_cycle
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Integer deliveryCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_id
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private Long accountId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    private static final long serialVersionUID = 1L;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.favorite_food_id_list
     *
     * @return the value of user_info.favorite_food_id_list
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getFavoriteFoodIdList() {
        return favoriteFoodIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.favorite_food_id_list
     *
     * @param favoriteFoodIdList the value for user_info.favorite_food_id_list
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setFavoriteFoodIdList(String favoriteFoodIdList) {
        this.favoriteFoodIdList = favoriteFoodIdList == null ? null : favoriteFoodIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.dislike_food_id_list
     *
     * @return the value of user_info.dislike_food_id_list
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getDislikeFoodIdList() {
        return dislikeFoodIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.dislike_food_id_list
     *
     * @param dislikeFoodIdList the value for user_info.dislike_food_id_list
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setDislikeFoodIdList(String dislikeFoodIdList) {
        this.dislikeFoodIdList = dislikeFoodIdList == null ? null : dislikeFoodIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.consumption_upper_limit
     *
     * @return the value of user_info.consumption_upper_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Integer getConsumptionUpperLimit() {
        return consumptionUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.consumption_upper_limit
     *
     * @param consumptionUpperLimit the value for user_info.consumption_upper_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setConsumptionUpperLimit(Integer consumptionUpperLimit) {
        this.consumptionUpperLimit = consumptionUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.consumption_lower_limit
     *
     * @return the value of user_info.consumption_lower_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Integer getConsumptionLowerLimit() {
        return consumptionLowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.consumption_lower_limit
     *
     * @param consumptionLowerLimit the value for user_info.consumption_lower_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setConsumptionLowerLimit(Integer consumptionLowerLimit) {
        this.consumptionLowerLimit = consumptionLowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.recipient
     *
     * @return the value of user_info.recipient
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.recipient
     *
     * @param recipient the value for user_info.recipient
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient == null ? null : recipient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reception_time_upper_limit
     *
     * @return the value of user_info.reception_time_upper_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getReceptionTimeUpperLimit() {
        return receptionTimeUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reception_time_upper_limit
     *
     * @param receptionTimeUpperLimit the value for user_info.reception_time_upper_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setReceptionTimeUpperLimit(String receptionTimeUpperLimit) {
        this.receptionTimeUpperLimit = receptionTimeUpperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.reception_time_lower_limit
     *
     * @return the value of user_info.reception_time_lower_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public String getReceptionTimeLowerLimit() {
        return receptionTimeLowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.reception_time_lower_limit
     *
     * @param receptionTimeLowerLimit the value for user_info.reception_time_lower_limit
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setReceptionTimeLowerLimit(String receptionTimeLowerLimit) {
        this.receptionTimeLowerLimit = receptionTimeLowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subscription_sate
     *
     * @return the value of user_info.subscription_sate
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Byte getSubscriptionSate() {
        return subscriptionSate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subscription_sate
     *
     * @param subscriptionSate the value for user_info.subscription_sate
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setSubscriptionSate(Byte subscriptionSate) {
        this.subscriptionSate = subscriptionSate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subscription_start_time
     *
     * @return the value of user_info.subscription_start_time
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Date getSubscriptionStartTime() {
        return subscriptionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subscription_start_time
     *
     * @param subscriptionStartTime the value for user_info.subscription_start_time
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setSubscriptionStartTime(Date subscriptionStartTime) {
        this.subscriptionStartTime = subscriptionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delivery_cycle
     *
     * @return the value of user_info.delivery_cycle
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Integer getDeliveryCycle() {
        return deliveryCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.delivery_cycle
     *
     * @param deliveryCycle the value for user_info.delivery_cycle
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setDeliveryCycle(Integer deliveryCycle) {
        this.deliveryCycle = deliveryCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_id
     *
     * @return the value of user_info.account_id
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_id
     *
     * @param accountId the value for user_info.account_id
     * @mbggenerated Sun Apr 08 16:35:09 CST 2018
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }



}

